name: Existing workflow test
on:
  issues:
    types:
      - closed

jobs:
  output-event-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "Header"
          subhead: "Latest issue closed by: ${{ github.actor }}"
          footer: ""
          repoCount: 0
